services:
  database:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: LIVE_CODING_DB
      POSTGRES_USER: LIVE_CODING_DB
      POSTGRES_PASSWORD: LIVE_CODING_DB
    restart: always